/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Abi Montes
 */
public class ViewMessage extends javax.swing.JFrame {

    /**
     * Creates new form ViewMessage
     */
    public ViewMessage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_rfc = new javax.swing.JPanel();
        jl_nombre = new javax.swing.JLabel();
        jl_ap = new javax.swing.JLabel();
        jl_am = new javax.swing.JLabel();
        jl_dia = new javax.swing.JLabel();
        jl_mes = new javax.swing.JLabel();
        jl_anio = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_ap = new javax.swing.JTextField();
        jtf_am = new javax.swing.JTextField();
        jtf_dia = new javax.swing.JTextField();
        jtf_mes = new javax.swing.JTextField();
        jtf_anio = new javax.swing.JTextField();
        jb_calcular = new javax.swing.JButton();
        jl_rfc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_rfc.setBackground(new java.awt.Color(204, 204, 204));

        jl_nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_nombre.setText("Nombre");
        jl_nombre.setToolTipText("");

        jl_ap.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_ap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_ap.setText("Apellido paterno");
        jl_ap.setToolTipText("");

        jl_am.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_am.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_am.setText("Apellido materno");
        jl_am.setToolTipText("");

        jl_dia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_dia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_dia.setText("Dia");
        jl_dia.setToolTipText("");

        jl_mes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_mes.setText("Mes");
        jl_mes.setToolTipText("");

        jl_anio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_anio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_anio.setText("Año");
        jl_anio.setToolTipText("");

        jtf_nombre.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N

        jtf_ap.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N

        jtf_am.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N

        jtf_dia.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N

        jtf_mes.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N

        jtf_anio.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N

        jb_calcular.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jb_calcular.setText("Calcular");

        jl_rfc.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        jl_rfc.setText("RFC:");

        javax.swing.GroupLayout jp_rfcLayout = new javax.swing.GroupLayout(jp_rfc);
        jp_rfc.setLayout(jp_rfcLayout);
        jp_rfcLayout.setHorizontalGroup(
            jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_rfcLayout.createSequentialGroup()
                .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_rfcLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_ap, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_rfcLayout.createSequentialGroup()
                                .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_nombre)
                                    .addComponent(jl_ap)
                                    .addComponent(jl_am)
                                    .addComponent(jtf_am, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp_rfcLayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jl_rfc)))
                                .addGap(70, 70, 70)
                                .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_dia)
                                    .addComponent(jl_mes)
                                    .addComponent(jtf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_anio)))))
                    .addGroup(jp_rfcLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jb_calcular)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jp_rfcLayout.setVerticalGroup(
            jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_rfcLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jl_dia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ap)
                    .addComponent(jl_mes))
                .addGap(7, 7, 7)
                .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_ap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_am)
                    .addComponent(jl_anio))
                .addGap(8, 8, 8)
                .addGroup(jp_rfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jl_rfc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_calcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_rfc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_calcular;
    public javax.swing.JLabel jl_am;
    public javax.swing.JLabel jl_anio;
    public javax.swing.JLabel jl_ap;
    public javax.swing.JLabel jl_dia;
    public javax.swing.JLabel jl_mes;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_rfc;
    public javax.swing.JPanel jp_rfc;
    public javax.swing.JTextField jtf_am;
    public javax.swing.JTextField jtf_anio;
    public javax.swing.JTextField jtf_ap;
    public javax.swing.JTextField jtf_dia;
    public javax.swing.JTextField jtf_mes;
    public javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
